name: Test

on:
  push:
    branches:
      - main
  pull_request:

env:
  GO111MODULE: on

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - uses: golangci/golangci-lint-action@v3.3.1
        with:
          version: latest
          args: --timeout 3m --verbose

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19'

      - name: Setup GO environment
        run: |
          go get -t .

      - name: Unit tests
        run: |
          sudo go test ./...
